### PR TITLE
fix providerlink requirement even if auth is disabled

### LINKED ISSUE #73: Fix initialisation of oidc, when auth enabled
if `AUTH_ENABLED:false` the provider link is still required

### PR DESCRIPTION
**Pull request by RabbITCybErSeC**

### CODE REVIEW

File: routes/routes.go [hunk 1]
```diff
@@ -15,31 +15,41 @@ import (
...
-	protectedRoutes.Use(auth.LoadAuthContext())
 
 	PublicRoutes(publicRoutes, authEnabled, authHandler)
 
-	protectedRoutes.Use(auth.Middleware([]string{"soarca_admin"}))
-	DashboardRoutes(protectedRoutes, authHandler)
+	if authEnabled {
+		protectedRoutes.Use(auth.LoadAuthContext())
+		protectedRoutes.Use(auth.Middleware([]string{requiredGroupPermission}))
+	}
```
Comment (MaartendeKruijf) [inline routes/routes.go]: Move protected routes into same authEnabled block

**Review by MaartendeKruijf — APPROVED** [review]
